apiVersion: v1
kind: ReplicationController
metadata:
  name: update-demo-glassfish
spec:
  replicas: 2
  selector:
    name: update-demo
    version: glassfish
  template:
    metadata:
      labels:
        name: update-demo
        version: glassfish
    spec:
      containers:
      - image: mkoster/glassfish
        name: update-demo
        ports:
        - containerPort: 80
          protocol: TCP
