apiVersion: v1
kind: ReplicationController
metadata:
  name: update-demo-jboss
spec:
  selector:
    name: update-demo
    version: jboss
  template:
    metadata:
      labels:
        name: update-demo
        version: jboss
    spec:
      containers:
      - image: mkoster/jboss
        name: update-demo
        ports:
        - containerPort: 80
          protocol: TCP
